name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create env file
        run: |
          touch .env
          echo ${{ secrets.ENV }} >> .env
          cat .env
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: yarn test-ci --key=04466a88-5192-4c3c-94d5-a7bd9d2a53bf
          parallel: true
      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: start
          if-no-files-found: error
          path: reports
